spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      add-mappings: false

server:
  port: 3001
