logging:
  config: classpath:log4j2-dev.xml

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/gistgarden-webservice?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootpw
  session:
    jdbc:
      schema: classpath:/sql/session-schema.sql
      initialize-schema: always
server:
  servlet:
    session:
      timeout: 120m

email:
  logEmailsInsteadOfSendingThem: true
  sendGrid:
    apiKey: "dummyApiKey"

website:
  mainSiteBaseUrl: 'http://localhost:8081'
