logging:
  config: classpath:log4j2-dev.xml


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysqlhost.srv.lan:3306/gistgarden-webservice?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${GG_DATABASE_USERNAME}
    password: ${GG_DATABASE_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 35s
  session:
    jdbc:
      schema: classpath:/sql/session-schema.sql
      initialize-schema: always


server:
  shutdown: graceful
  servlet:
    session:
      timeout: 20m

email:
  sendGrid:
    apiKey: ${GG_SEND_GRID_API_KEY}
