FROM gradle:7.6-jdk17-alpine AS builder

WORKDIR /app

COPY build.gradle.kts ./
COPY settings.gradle.kts ./
RUN gradle resolveDependencies --no-daemon --scan
#RUN cat /app/build/reports/profile/*

COPY src ./src/

RUN gradle bootJar --no-daemon


FROM builder AS tester
RUN gradle test --no-daemon


FROM amazoncorretto:17.0.10 AS release

EXPOSE 3001

HEALTHCHECK --interval=15s \
            --retries=3 \
            --start-period=1m \
            --timeout=5s \
            CMD curl --fail http://localhost:3001/actuator/health || exit 1

ENTRYPOINT ["java"]

ENV APP_HOME=/app

RUN yum -y install shadow-utils.x86_64 && \
    groupadd -g 10030 spring-user && \
    useradd -m -u 10030 -g spring-user spring-user

RUN mkdir -p ${APP_HOME}/src/main/resources/


COPY --chown=spring-user:spring-user src/main/resources/ ${APP_HOME}/src/main/resources/

COPY --from=builder --chown=spring-user:spring-user /app/build/libs/gistgarden-webservice.jar ${APP_HOME}/gistgarden-webservice.jar

RUN chown -R spring-user:spring-user ${APP_HOME}
USER spring-user
WORKDIR ${APP_HOME}